In [1]:
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import csv

In [2]:
df19_7to10=pd.read_csv('2019년 출근 시간 대여소 정리.csv')
df20_7to10=pd.read_csv('2020년 출근 시간 대여소 정리.csv')

df19_17to20=pd.read_csv('2019년 퇴근 시간 대여소 정리.csv')
df20_17to20=pd.read_csv('2020년 퇴근 시간 대여소 정리.csv')

In [3]:
df19_7to10.head(10)

,Unnamed: 0,station,보관소(대여소)명,자치구,위도,경도,N_out,N_in,Count,Flow,degree_centrality,pagerank
0,680,113,홍대입구역 2번출구 앞,마포구,37.557499,126.923805,5647,20570,26217,0.569211,0.200770,0.001383
1,885,2701,마곡나루역 5번출구 뒤편,강서구,37.565201,126.827316,12729,12112,24841,-0.024838,0.087235,0.000665
2,1368,1210,롯데월드타워(잠실역2번출구 쪽),송파구,37.513126,127.100960,6192,13685,19877,0.376968,0.181527,0.001295
3,893,1911,구로디지털단지역 앞,구로구,37.484940,126.901321,6821,9610,16431,0.169740,0.192431,0.001362
4,234,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,5810,9990,15800,0.264557,0.241180,0.001661
5,189,563,성동세무서 건너편,성동구,37.547913,127.062752,1943,13427,15370,0.747170,0.157152,0.001093
6,370,1308,안암로터리 버스정류장 앞,성북구,37.582592,127.028976,3859,11149,15008,0.485741,0.197563,0.001346
7,1003,207,여의나루역 1번출구 앞,영등포구,37.526989,126.932098,8576,5497,14073,-0.218788,0.255933,0.001746
8,1016,222,시범아파트버스정류장 옆,영등포구,37.519436,126.937599,4117,9936,14053,0.414075,0.172547,0.001182
9,998,202,국민일보 앞,영등포구,37.528816,126.924530,2611,11353,13964,0.626038,0.207826,0.001418

In [4]:
df19_17to20.head(10)

,Unnamed: 0,station,보관소(대여소)명,자치구,위도,경도,N_out,N_in,Count,Flow,degree_centrality,pagerank
0,234,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,23898,28508,52406,0.087967,0.241180,0.001887
1,1003,207,여의나루역 1번출구 앞,영등포구,37.526989,126.932098,24183,25538,49721,0.027252,0.255933,0.002212
2,680,113,홍대입구역 2번출구 앞,마포구,37.557499,126.923805,20393,15734,36127,-0.128962,0.200770,0.001313
3,1369,1210,롯데월드타워(잠실역2번출구 쪽),송파구,37.513126,127.100960,20452,15086,35538,-0.150993,0.181527,0.001241
4,1187,2219,"고속터미널역 8-1번, 8-2번 출구 사이",서초구,37.506199,127.003944,15241,15777,31018,0.017280,0.313663,0.002278
5,1125,2102,봉림교 교통섬,관악구,37.484230,126.926392,13694,16056,29750,0.079395,0.158435,0.001041
6,885,2701,마곡나루역 5번출구 뒤편,강서구,37.565201,126.827316,15952,12633,28585,-0.116110,0.087235,0.000716
7,225,3533,건대입구역 사거리(롯데백화점),광진구,37.539139,127.070618,14271,13123,27394,-0.041907,0.163566,0.001367
8,703,152,마포구민체육센터 앞,마포구,37.556610,126.898018,10209,16549,26758,0.236938,0.177678,0.001279
9,889,1906,신도림역 1번 출구 앞,구로구,37.509720,126.890099,13829,11114,24943,-0.108848,0.223220,0.001342

In [5]:
df20_7to10.head(10)

,Unnamed: 0,station,보관소(대여소)명,자치구,위도,경도,N_out,N_in,Count,Flow,degree_centrality,pagerank
0,1179,2701,마곡나루역 5번출구 뒤편,강서구,37.565201,126.827316,12094,10962,23056,-0.049098,0.088608,0.000602
1,1222,1911,구로디지털단지역 앞,구로구,37.484940,126.901321,6951,9893,16844,0.174662,0.167370,0.001113
2,1832,1210,롯데월드타워(잠실역2번출구 쪽),송파구,37.513126,127.100960,6022,9787,15809,0.238155,0.150023,0.001035
3,1377,222,시범아파트버스정류장 옆,영등포구,37.519436,126.937599,3883,10287,14170,0.451941,0.154243,0.000997
4,1366,210,IFC몰,영등포구,37.526066,126.925537,3323,10332,13655,0.513292,0.213783,0.001384
5,1364,207,여의나루역 1번출구 앞,영등포구,37.526989,126.932098,7856,5703,13559,-0.158788,0.270511,0.001741
6,324,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,5350,7965,13315,0.196395,0.244257,0.001588
7,403,646,장한평역 1번출구 (국민은행앞),동대문구,37.561867,127.064377,5853,7434,13287,0.118988,0.160338,0.001051
8,1568,2177,신대방역 2번 출구,관악구,37.487129,126.913017,6110,6938,13048,0.063458,0.139709,0.000928
9,1173,1195,코오롱One&Only타워,강서구,37.564129,126.834312,975,11843,12818,0.847870,0.079231,0.000544

In [6]:
df20_17to20.head(10)

,Unnamed: 0,station,보관소(대여소)명,자치구,위도,경도,N_out,N_in,Count,Flow,degree_centrality,pagerank
0,324,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,26359,28990,55349,0.047535,0.516838,0.001758
1,1365,207,여의나루역 1번출구 앞,영등포구,37.526989,126.932098,25653,25368,51021,-0.005586,0.593545,0.001995
2,1526,2102,봉림교 교통섬,관악구,37.484230,126.926392,15473,18589,34062,0.091480,0.273620,0.000943
3,953,152,마포구민체육센터 앞,마포구,37.556610,126.898018,13992,19021,33013,0.152334,0.359214,0.001237
4,1604,2219,"고속터미널역 8-1번, 8-2번 출구 사이",서초구,37.506199,127.003944,14571,14749,29320,0.006071,0.565949,0.001909
5,1138,1153,"발산역 1번, 9번 인근 대여소",강서구,37.558910,126.838097,14832,14111,28943,-0.024911,0.199719,0.000695
6,1180,2701,마곡나루역 5번출구 뒤편,강서구,37.565201,126.827316,14492,13212,27704,-0.046203,0.185688,0.000651
7,1424,272,당산육갑문,영등포구,37.535339,126.903679,12955,13975,26930,0.037876,0.472404,0.001592
8,265,565,옥수역 3번출구,성동구,37.541363,127.017662,11900,13773,25673,0.072956,0.539757,0.001817
9,273,583,청계천 생태교실 앞,성동구,37.567970,127.046890,12107,12838,24945,0.029304,0.496726,0.001673

In [7]:
x_19=pd.merge(df19_7to10,df19_17to20, left_on='station', right_on='station', how='inner')
x_20=pd.merge(df20_7to10,df20_17to20, left_on='station', right_on='station', how='inner')
x_7to10=pd.merge(df19_7to10,df20_7to10, left_on='station', right_on='station', how='inner')
x_17to20=pd.merge(df19_17to20,df20_17to20, left_on='station', right_on='station', how='inner')

# 2019 출근-퇴근

In [8]:
df_count=x_19.copy()[['station','보관소(대여소)명_x','자치구_x','Count_x','Count_y']]
df_count['Net']=df_count['Count_y']-df_count['Count_x']
df_count = df_count.sort_values(by='Net' ,ascending=False)
# 출근<<퇴근
df_count.head(10)

     station              보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
4        502            뚝섬유원지역 1번출구 앞   광진구    15800    52406  36606
7        207             여의나루역 1번출구 앞  영등포구    14073    49721  35648
150     2219  고속터미널역 8-1번, 8-2번 출구 사이   서초구     5939    31018  25079
52      2102                  봉림교 교통섬   관악구     8830    29750  20920
113      152               마포구민체육센터 앞   마포구     6526    26758  20232
144     1222            잠실새내역 5번 출구 뒤   송파구     6012    23831  17819
37      3533         건대입구역 사거리(롯데백화점)   광진구     9829    27394  17565
166      272                    당산육갑문  영등포구     5711    22865  17154
2       1210        롯데월드타워(잠실역2번출구 쪽)   송파구    19877    35538  15661
61       907                  CJ 드림시티   은평구     8425    23654  15229

In [9]:
df_count.tail(10)

     station       보관소(대여소)명_x 자치구_x  Count_x  Count_y   Net
182      300             정동사거리    중구     5600     3565 -2035
141      378          청계7가 사거리    중구     6024     3864 -2160
38       217          NH농협은행 앞  영등포구     9821     7409 -2412
31       578          성동세무서 부근   성동구    10546     7732 -2814
93      3523  건국대학교 과학관(이과대) 앞   광진구     7035     3728 -3307
56       308         광화문 S타워 앞   종로구     8644     5150 -3494
21       514     성수사거리 버스정류장 앞   성동구    11878     7975 -3903
14      1195     코오롱One&Only타워   강서구    13278     9362 -3916
5        563         성동세무서 건너편   성동구    15370    10325 -5045
30       213               KT앞  영등포구    10552     4464 -6088

# 2020 출근-퇴근

In [10]:
df_count=x_20.copy()[['station','보관소(대여소)명_x','자치구_x','Count_x','Count_y']]
df_count['Net']=df_count['Count_y']-df_count['Count_x']
df_count = df_count.sort_values(by='Net' ,ascending=False)
# 출근<<퇴근
df_count.head(10)

     station              보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
6        502            뚝섬유원지역 1번출구 앞   광진구    13315    55349  42034
5        207             여의나루역 1번출구 앞  영등포구    13559    51021  37462
63       152               마포구민체육센터 앞   마포구     7380    33013  25633
34      2102                  봉림교 교통섬   관악구     9079    34062  24983
143     2219  고속터미널역 8-1번, 8-2번 출구 사이   서초구     5534    29320  23786
131      272                    당산육갑문  영등포구     5695    26930  21235
20      1153        발산역 1번, 9번 인근 대여소   강서구    10763    28943  18180
79       583               청계천 생태교실 앞   성동구     6872    24945  18073
47       565                 옥수역 3번출구   성동구     8253    25673  17420
54      3533         건대입구역 사거리(롯데백화점)   광진구     7944    24819  16875

In [11]:
df_count.tail(10)

     station    보관소(대여소)명_x 자치구_x  Count_x  Count_y   Net
70       508     성수아카데미타워 앞   성동구     7006     5176 -1830
333     2727   서울식물원 잔디마당 앞   강서구     3856     1921 -1935
115     1962       가리봉동주민센터   구로구     6057     3998 -2059
41       308      광화문 S타워 앞   종로구     8568     6506 -2062
49       578       성동세무서 부근   성동구     8216     5407 -2809
35       514  성수사거리 버스정류장 앞   성동구     9032     6030 -3002
72      1194           센서텍㈜   강서구     6979     3888 -3091
46       213            KT앞  영등포구     8335     4289 -4046
10       563      성동세무서 건너편   성동구    12559     7935 -4624
9       1195  코오롱One&Only타워   강서구    12818     7693 -5125

# 2019 vs. 2020 (출근시간)

In [12]:
df_count=x_7to10.copy()[['station','보관소(대여소)명_x','자치구_x','Count_x','Count_y']]
df_count['Net']=df_count['Count_y']-df_count['Count_x']
df_count = df_count.sort_values(by='Net' ,ascending=False)
# 2020>>2019
df_count.head(10)

      station            보관소(대여소)명_x 자치구_x  Count_x  Count_y   Net
472      2801              대륭포스트타워1차   구로구     3368     8061  4693
97       1152                 마곡역교차로   강서구     6925    11085  4160
839       765              오목교역 3번출구   양천구     2149     6057  3908
92        263              근로자회관 사거리  영등포구     7071    10117  3046
796      1180  마곡엠밸리 15단지(1502동) 건너편   강서구     2242     5082  2840
26        646      장한평역 1번출구 (국민은행앞)  동대문구    10741    13287  2546
1250      766              신목동역 3번출구   양천구      990     3292  2302
300       370        시청역(2호선) 9번출구 뒤    중구     4423     6660  2237
54       1153      발산역 1번, 9번 인근 대여소   강서구     8711    10763  2052
454       729            서부식자재마트 건너편   양천구     3442     5387  1945

In [13]:
# 2020<<2019
df_count.tail(10)

     station        보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
234      125           서강대 남문 옆   마포구     4958     1161  -3797
2       1210  롯데월드타워(잠실역2번출구 쪽)   송파구    19877    15809  -4068
86       126           서강대 후문 옆   마포구     7253     3169  -4084
93      3523   건국대학교 과학관(이과대) 앞   광진구     7035     2622  -4413
6       1308      안암로터리 버스정류장 앞   성북구    15008    10439  -4569
19       415        DMC역 9번출구 앞   마포구    12359     7664  -4695
11       409           누리꿈스퀘어 옆   마포구    13754     8905  -4849
15       590      건국대학교 (입학정보관)   광진구    13021     5436  -7585
24       592         건국대학교 학생회관   광진구    10822     3088  -7734
0        113       홍대입구역 2번출구 앞   마포구    26217     9659 -16558

# 2019 vs. 2020 (퇴근시간)

In [14]:
df_count=x_17to20.copy()[['station','보관소(대여소)명_x','자치구_x','Count_x','Count_y']]
df_count['Net']=df_count['Count_y']-df_count['Count_x']
df_count = df_count.sort_values(by='Net' ,ascending=False)
# 2020>>2019
df_count.head(10)

     station        보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
398      765          오목교역 3번출구   양천구     6742    18768  12026
30      2177         신대방역 2번 출구   관악구    17079    23584   6505
15      1153  발산역 1번, 9번 인근 대여소   강서구    22569    28943   6374
8        152         마포구민체육센터 앞   마포구    26758    33013   6255
427     1152             마곡역교차로   강서구     6449    12664   6215
191     1827   독산보도육교 앞 자전거 보관소   금천구     9530    15277   5747
21       583         청계천 생태교실 앞   성동구    19323    24945   5622
87      1149          신방화역환승주차장   강서구    12718    18197   5479
706      766          신목동역 3번출구   양천구     4461     9828   5367
82      3511           응봉역 1번출구   성동구    13033    18345   5312

In [15]:
# 2020<<2019
df_count.tail(10)

     station        보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
117      238         제2구민체육센타 앞  영등포구    11300     5629  -5671
50       421             마포구청 앞   마포구    14837     9084  -5753
62      1243           문정 법조단지7   송파구    14066     8110  -5956
184      592         건국대학교 학생회관   광진구     9765     3705  -6060
29      1251           석촌역 2번출구   송파구    17382    11288  -6094
10      1222      잠실새내역 5번 출구 뒤   송파구    23831    17459  -6372
34      1212         송파역 2번 출구앞   송파구    16572     9603  -6969
51       590      건국대학교 (입학정보관)   광진구    14765     5700  -9065
3       1210  롯데월드타워(잠실역2번출구 쪽)   송파구    35538    24888 -10650
2        113       홍대입구역 2번출구 앞   마포구    36127    14212 -21915

In [16]:
x_7to10['count_net']=x_7to10['Count_y']-x_7to10['Count_x']
x_7to10['flow_net']=x_7to10['Flow_y']-x_7to10['Flow_x']
x_7to10['deg_net']=x_7to10['degree_centrality_y']-x_7to10['degree_centrality_x']
x_7to10['pg_net']=x_7to10['pagerank_y']-x_7to10['pagerank_x']
x_7to10['count_per']=x_7to10['Count_y']/x_7to10['Count_x']

k1=x_7to10.copy()[['station','보관소(대여소)명_x','자치구_x','위도_x','경도_x','count_per','count_net','flow_net','deg_net','pg_net']]
k1.columns=['station','name','region','latitude','longitude','usage_per','usage','flow','d_c','pr']
k1

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
0,113,홍대입구역 2번출구 앞,마포구,37.557499,126.923805,0.368425,-16558,-0.016876,-0.079813,-0.000588
1,2701,마곡나루역 5번출구 뒤편,강서구,37.565201,126.827316,0.928143,-1785,-0.024260,0.001372,-0.000062
2,1210,롯데월드타워(잠실역2번출구 쪽),송파구,37.513126,127.100960,0.795341,-4068,-0.138813,-0.031503,-0.000260
3,1911,구로디지털단지역 앞,구로구,37.484940,126.901321,1.025135,413,0.004921,-0.025061,-0.000248
4,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,0.842722,-2485,-0.068162,0.003077,-0.000073
...,...,...,...,...,...,...,...,...,...,...
1508,1007,암사동 선사유적지,강동구,37.559517,127.130844,0.869565,-15,-0.061739,-0.005598,-0.000061
1509,2391,구룡터널 입구(개포1단지아파트),강남구,37.475986,127.059624,0.708738,-30,0.303232,-0.012901,-0.000106
1510,2287,능안마을입구,서초구,37.455620,127.067101,0.474227,-51,0.287315,-0.005377,-0.000058
1511,937,상림마을 롯데캐슬2단지 옆,은평구,37.645851,126.923798,1.521739,48,-0.474534,-0.002834,-0.000044
1512,465,삼청공원 앞,종로구,37.587605,126.983597,18.062500,273,0.266869,0.019716,0.000100

In [17]:
#df_count = df_count.sort_values(by='Net' ,ascending=False)
k1=k1.sort_values(by='usage_per',ascending=False)
k1

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
1512,465,삼청공원 앞,종로구,37.587605,126.983597,18.062500,273,0.266869,0.019716,0.000100
1505,664,서울시립대 대학본부,동대문구,37.584129,127.057938,8.496183,982,-0.166430,0.033783,0.000189
1406,2185,대학동 고시촌,관악구,37.470467,126.938652,3.707904,1576,0.139129,0.019403,0.000091
1250,766,신목동역 3번출구,양천구,37.544260,126.883250,3.325253,2302,-0.021476,0.021783,0.000075
1504,449,일성아파트,종로구,37.608719,126.972862,2.828358,245,-0.060292,0.005826,0.000014
...,...,...,...,...,...,...,...,...,...,...
1418,1675,월계문화체육센터,노원구,37.626942,127.055130,0.233577,-420,0.507641,-0.017982,-0.000149
1379,1114,서남물재생센터 버스정류장,강서구,37.572781,126.826279,0.207407,-535,0.139788,-0.029110,-0.000227
899,3524,세종대학교,광진구,37.550236,127.073822,0.201439,-1554,0.049369,-0.039418,-0.000285
1497,3527,왕십리 자이아파트,성동구,37.561790,127.024391,0.170455,-146,-0.058333,-0.028296,-0.000197
1506,2288,안골마을입구,서초구,37.455608,127.064453,0.154472,-104,0.078733,-0.013321,-0.000120

In [18]:
k1.head(30)

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
1512,465,삼청공원 앞,종로구,37.587605,126.983597,18.062500,273,0.266869,0.019716,0.000100
1505,664,서울시립대 대학본부,동대문구,37.584129,127.057938,8.496183,982,-0.166430,0.033783,0.000189
1406,2185,대학동 고시촌,관악구,37.470467,126.938652,3.707904,1576,0.139129,0.019403,0.000091
1250,766,신목동역 3번출구,양천구,37.544260,126.883250,3.325253,2302,-0.021476,0.021783,0.000075
1504,449,일성아파트,종로구,37.608719,126.972862,2.828358,245,-0.060292,0.005826,0.000014
839,765,오목교역 3번출구,양천구,37.524776,126.875481,2.818520,3908,0.075625,0.036587,0.000167
1467,440,하늘공원 입구,마포구,37.570006,126.881149,2.817175,656,-0.128573,0.018763,0.000087
1438,2175,신림동걷고싶은문화의거리입구,관악구,37.487301,126.928703,2.706278,761,-0.140318,0.017280,0.000081
1344,1936,개봉역 1번 출구 자전거보관서쪽,구로구,37.494282,126.859215,2.540079,1172,-0.128143,0.008792,0.000037
472,2801,대륭포스트타워1차,구로구,37.484371,126.895424,2.393409,4693,-0.022641,0.018499,0.000065
1466,1858,석수역1번출구 앞 (SK주유소),금천구,37.437271,126.902687,2.354571,489,0.023073,0.007239,0.000012
1481,600,휘경2동 주민센터,동대문구,37.589912,127.068680,2.306818,345,0.195664,0.003808,-0.000007
796,1180,마곡엠밸리 15단지(1502동) 건너편,강서구,37.557468,126.829720,2.266726,2840,0.466464,0.014444,0.000041
1431,1820,신한은행 시흥대로금융센터지점,금천구,37.443340,126.903358,2.201299,555,-0.095455,0.002250,-0.000012
1477,2064,흑석한강푸르지오 106동앞,동작구,37.505356,126.966179,2.189542,364,0.018749,0.006299,0.000011
1487,2040,비계 버스정류소,동작구,37.506359,126.969078,2.165939,267,-0.141657,0.002647,-0.000008
1244,464,삼청동 골목,종로구,37.584190,126.981697,2.154224,1175,0.143390,0.012468,0.000042
1330,1993,금강수목원아파트 앞,구로구,37.489380,126.834198,2.142145,916,0.251670,0.005261,0.000023
1492,1969,궁동생태공원,구로구,37.501904,126.828964,2.065657,211,0.237658,-0.000045,-0.000032
1399,1109,공항시장역 4번출구,강서구,37.563347,126.810486,2.003356,598,0.042657,-0.000584,-0.000052
1460,2609,보성중고등학교 후문 앞,송파구,37.520489,127.135201,1.989848,390,-0.512613,0.014391,0.000064
1189,1639,희성오피앙,노원구,37.680313,127.055069,1.958692,1114,0.046597,0.000281,-0.000041
1358,1058,고덕숲 아이파크 1,강동구,37.553471,127.165001,1.925676,685,-0.250583,0.012613,0.000062
806,1190,마곡역 교차로(2번출구),강서구,37.560501,126.826653,1.881256,1937,0.024014,0.003265,-0.000023
974,1998,고척교 교차로,구로구,37.498569,126.871521,1.858050,1487,-0.079854,0.002239,-0.000047
1292,399,서울역 센트럴 자이아파트,중구,37.554108,126.965408,1.843715,745,-0.057310,-0.000111,-0.000030
770,1720,도봉구청 옆(중랑천변),도봉구,37.668671,127.047981,1.792130,1852,-0.006851,0.019409,0.000084
1445,810,이태원지하보도,용산구,37.538410,126.986649,1.740566,314,0.149205,-0.000731,-0.000032
1458,1992,구로구배드민턴실내체육관 앞,구로구,37.491798,126.832420,1.739348,295,-0.357674,0.006297,0.000025
1348,1340,광운초등학교 앞,성북구,37.619560,127.053802,1.736772,557,-0.065064,-0.000088,-0.000049

In [20]:
k1.to_csv('Net_7to10.csv')

In [21]:
x_17to20['count_net']=x_17to20['Count_y']-x_17to20['Count_x']
x_17to20['flow_net']=x_17to20['Flow_y']-x_17to20['Flow_x']
x_17to20['deg_net']=x_17to20['degree_centrality_y']-x_17to20['degree_centrality_x']
x_17to20['pg_net']=x_17to20['pagerank_y']-x_17to20['pagerank_x']
x_17to20['count_per']=x_17to20['Count_y']/x_17to20['Count_x']

k=x_17to20.copy()[['station','보관소(대여소)명_x','자치구_x','위도_x','경도_x','count_per','count_net','flow_net','deg_net','pg_net']]
k.columns=['station','name','region','latitude','longitude','usage_per','usage','flow','d_c','pr']
k

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
0,502,뚝섬유원지역 1번출구 앞,광진구,37.531860,127.067192,1.056158,2943,-0.040432,0.275658,-0.000129
1,207,여의나루역 1번출구 앞,영등포구,37.526989,126.932098,1.026146,1300,-0.032838,0.337612,-0.000217
2,113,홍대입구역 2번출구 앞,마포구,37.557499,126.923805,0.393390,-21915,-0.021334,0.055545,-0.000444
3,1210,롯데월드타워(잠실역2번출구 쪽),송파구,37.513126,127.100960,0.700321,-10650,0.015747,0.114077,-0.000208
4,2219,"고속터미널역 8-1번, 8-2번 출구 사이",서초구,37.506199,127.003944,0.945258,-1698,-0.011209,0.252287,-0.000369
...,...,...,...,...,...,...,...,...,...,...
1509,2391,구룡터널 입구(개포1단지아파트),강남구,37.475986,127.059624,0.680851,-45,-0.183067,-0.007777,-0.000073
1510,664,서울시립대 대학본부,동대문구,37.584129,127.057938,7.569343,900,-0.041909,0.045357,0.000110
1511,2286,탑성마을입구,서초구,37.458549,127.055885,1.375000,36,-0.054924,0.001096,-0.000044
1512,465,삼청공원 앞,종로구,37.587605,126.983597,10.781250,313,0.234420,0.036964,0.000074
1513,2394,개포래미안포레스트아파트 107동 앞,강남구,37.479092,127.055397,7.333333,76,-0.090909,0.013390,0.000016

In [22]:
k.to_csv('Net_17to20.csv')

In [23]:
#df_count = df_count.sort_values(by='Net' ,ascending=False)
k=k.sort_values(by='usage_per',ascending=False)
k

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
1512,465,삼청공원 앞,종로구,37.587605,126.983597,10.781250,313,0.234420,0.036964,0.000074
1510,664,서울시립대 대학본부,동대문구,37.584129,127.057938,7.569343,900,-0.041909,0.045357,0.000110
1513,2394,개포래미안포레스트아파트 107동 앞,강남구,37.479092,127.055397,7.333333,76,-0.090909,0.013390,0.000016
1445,1058,고덕숲 아이파크 1,강동구,37.553471,127.165001,3.990136,2425,0.109991,0.061166,0.000149
1411,2185,대학동 고시촌,관악구,37.470467,126.938652,3.737271,2688,0.040775,0.062276,0.000146
...,...,...,...,...,...,...,...,...,...,...
1343,1910,낙원교회 맞은편,구로구,37.497505,126.884377,0.246855,-958,0.213897,-0.009861,-0.000233
1285,3524,세종대학교,광진구,37.550236,127.073822,0.239696,-1199,0.080388,-0.031082,-0.000230
925,591,건국대학교 (행정관),광진구,37.542778,127.075371,0.217771,-2597,-0.311993,-0.033059,-0.000201
791,1018,둔촌 주공 GS 맞은편,강동구,37.524681,127.135406,0.207490,-3132,-0.051839,0.001445,-0.000246
1360,1114,서남물재생센터 버스정류장,강서구,37.572781,126.826279,0.089934,-1103,-0.204802,-0.020713,-0.000179

In [24]:
k.head(30)

,station,name,region,latitude,longitude,usage_per,usage,flow,d_c,pr
1512,465,삼청공원 앞,종로구,37.587605,126.983597,10.781250,313,0.234420,0.036964,0.000074
1510,664,서울시립대 대학본부,동대문구,37.584129,127.057938,7.569343,900,-0.041909,0.045357,0.000110
1513,2394,개포래미안포레스트아파트 107동 앞,강남구,37.479092,127.055397,7.333333,76,-0.090909,0.013390,0.000016
1445,1058,고덕숲 아이파크 1,강동구,37.553471,127.165001,3.990136,2425,0.109991,0.061166,0.000149
1411,2185,대학동 고시촌,관악구,37.470467,126.938652,3.737271,2688,0.040775,0.062276,0.000146
1300,2175,신림동걷고싶은문화의거리입구,관악구,37.487301,126.928703,3.072338,3094,-0.033349,0.098986,0.000112
398,765,오목교역 3번출구,양천구,37.524776,126.875481,2.783744,12026,-0.033617,0.162531,0.000048
1409,464,삼청동 골목,종로구,37.584190,126.981697,2.737538,1708,-0.028207,0.055367,0.000077
1500,449,일성아파트,종로구,37.608719,126.972862,2.496732,458,-0.211768,0.057223,0.000037
920,2801,대륭포스트타워1차,구로구,37.484371,126.895424,2.374552,4602,-0.002106,0.088844,0.000020
1348,709,신정3동 현장민원실 앞,양천구,37.511585,126.841560,2.309221,1647,0.151925,0.043527,0.000033
1251,1340,광운초등학교 앞,성북구,37.619560,127.053802,2.302617,2290,0.064477,0.077404,0.000009
706,766,신목동역 3번출구,양천구,37.544260,126.883250,2.203093,5367,-0.051510,0.151025,0.000022
1392,1993,금강수목원아파트 앞,구로구,37.489380,126.834198,2.171163,1259,-0.011761,0.033236,0.000050
1277,440,하늘공원 입구,마포구,37.570006,126.881149,2.119122,1785,-0.043409,0.087801,0.000025
1477,1054,말우물 어린이 공원,강동구,37.560009,127.169579,2.088608,602,-0.060146,0.021917,-0.000006
1502,1855,성지아파트 옆 도로변,금천구,37.451321,126.897621,1.978947,279,0.237999,0.016491,0.000013
427,1152,마곡역교차로,강서구,37.558666,126.826614,1.963715,6215,0.012564,0.041148,-0.000004
1265,1858,석수역1번출구 앞 (SK주유소),금천구,37.437271,126.902687,1.902597,1529,-0.084474,0.091756,-0.000035
1238,759,보아스아파트 앞,양천구,37.524071,126.838600,1.896799,1625,-0.136587,0.056570,0.000034
1244,972,수색역,은평구,37.582180,126.894943,1.887069,1571,-0.096150,0.082121,0.000049
819,1199,우장산역 3번출구,강서구,37.547821,126.836128,1.833464,3188,-0.010195,0.061154,-0.000016
1451,1105,방화근린공원,강서구,37.581623,126.812653,1.830931,634,0.026807,0.018055,-0.000015
1003,1639,희성오피앙,노원구,37.680313,127.055069,1.794239,2316,-0.002473,0.053469,-0.000009
1383,1971,오정초교 앞 보도육교,구로구,37.490723,126.826393,1.788204,882,-0.027072,0.059215,-0.000005
1490,1969,궁동생태공원,구로구,37.501904,126.828964,1.786571,328,-0.032517,0.027022,-0.000007
1128,1994,삼성전자 물류센터 앞,구로구,37.496998,126.871780,1.780887,1814,0.060223,0.061835,-0.000002
1266,1360,정릉역,성북구,37.603096,127.013504,1.777383,1313,0.001444,0.076535,0.000048
886,1998,고척교 교차로,구로구,37.498569,126.871521,1.769471,2707,0.033557,0.070269,-0.000097
494,1824,독산근린공원 입구,금천구,37.464550,126.883728,1.755847,4492,-0.106337,0.099615,-0.000068

# Tool

## Count

In [25]:
df_count=x.copy()[['station','보관소(대여소)명_x','자치구_x','Count_x','Count_y']]
df_count

NameError: name 'x' is not defined

In [26]:
df_count['Net']=df_count['Count_y']-df_count['Count_x']
df_count = df_count.sort_values(by='Net' ,ascending=False)
df_count.head(10)

     station        보관소(대여소)명_x 자치구_x  Count_x  Count_y    Net
398      765          오목교역 3번출구   양천구     6742    18768  12026
30      2177         신대방역 2번 출구   관악구    17079    23584   6505
15      1153  발산역 1번, 9번 인근 대여소   강서구    22569    28943   6374
8        152         마포구민체육센터 앞   마포구    26758    33013   6255
427     1152             마곡역교차로   강서구     6449    12664   6215
191     1827   독산보도육교 앞 자전거 보관소   금천구     9530    15277   5747
21       583         청계천 생태교실 앞   성동구    19323    24945   5622
87      1149          신방화역환승주차장   강서구    12718    18197   5479
706      766          신목동역 3번출구   양천구     4461     9828   5367
82      3511           응봉역 1번출구   성동구    13033    18345   5312

In [ ]:
df_count.tail(10)

## Flow

In [ ]:
df_flow=x.copy()[['station','보관소(대여소)명_x','자치구_x','Flow_x','Flow_y']]
df_flow19=x.copy()[['station','보관소(대여소)명_x','자치구_x','Flow_x']]
df_flow20=x.copy()[['station','보관소(대여소)명_x','자치구_x','Flow_y']]

In [ ]:
df_flow['Net']=df_flow['Flow_y']-df_flow['Flow_x']
df_flow = df_flow.sort_values(by='Net' ,ascending=False)
# 반납>>대여
df_flow.head(10)

In [ ]:
# 대여>>반납
df_flow.tail(10)

## Degree Centrality

In [ ]:
df_deg=x.copy()[['station','보관소(대여소)명_x','자치구_x','degree_centrality_x','degree_centrality_y']]
df_deg19=x.copy()[['station','보관소(대여소)명_x','자치구_x','degree_centrality_y']]
df_deg20=x.copy()[['station','보관소(대여소)명_x','자치구_x','degree_centrality_y']]
df_deg['Net']=df_deg['degree_centrality_y']-df_deg['degree_centrality_x']
df_deg = df_deg.sort_values(by='Net' ,ascending=False)
df_deg.head(10)

In [ ]:
df_deg.tail(10)

## Pagerank

In [ ]:
df_pg=x.copy()[['station','보관소(대여소)명_x','자치구_x','pagerank_x','pagerank_y']]
df_pg19=x.copy()[['station','보관소(대여소)명_x','자치구_x','pagerank_y']]
df_pg20=x.copy()[['station','보관소(대여소)명_x','자치구_x','pagerank_y']]
df_pg['Net']=df_pg['pagerank_y']-df_pg['pagerank_x']
df_pg = df_pg.sort_values(by='Net' ,ascending=False)
df_pg.head(10)

In [ ]:
df_pg.tail(10)